create or replace TABLE ORDERS (
	ORDERID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	CUSTOMERID NUMBER(38,0),
	SHIPMENTTRACKINGNO VARCHAR(20),
	ORDERSTATUS VARCHAR(20),
	PRODUCTDESCRIPTION VARCHAR(60),
	OUTLETID VARCHAR(20),
	PRODUCTID VARCHAR(20)
	
);